# Generated by Django 3.0.4 on 2020-03-14 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdetails',
            name='check_in',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='workingdetails',
            name='check_out',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='workingdetails',
            name='vacation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeavingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default=datetime.time(0, 0))),
                ('end', models.TimeField(default=datetime.time(0, 0))),
                ('working_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.WorkingDetails')),
            ],
        ),
    ]
