# Generated by Django 3.0.4 on 2020-03-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200314_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingdetails',
            options={'ordering': ['date']},
        ),
    ]
