# Generated by Django 3.0.4 on 2020-03-14 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200314_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdetails',
            name='check_in',
            field=models.DateTimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='workingdetails',
            name='check_out',
            field=models.DateTimeField(default=datetime.time(0, 0)),
        ),
    ]
