# Generated by Django 3.0.4 on 2020-03-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200314_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavingtime',
            name='working_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavingTimes', to='employee.WorkingDetails'),
        ),
    ]
