# Generated by Django 3.0.4 on 2020-03-15 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200314_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingdetails',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='leavingtime',
            name='working_details',
        ),
        migrations.AddField(
            model_name='leavingtime',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
