# Generated by Django 3.0.4 on 2020-03-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20200315_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeavingTime',
        ),
    ]
