# Generated by Django 3.0.4 on 2020-03-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_leavingtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavingtime',
            options={'ordering': ['working_details']},
        ),
        migrations.AlterModelOptions(
            name='workingdetails',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='leavingtime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leavingtime',
            name='user',
        ),
        migrations.AddField(
            model_name='leavingtime',
            name='working_details',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.WorkingDetails'),
            preserve_default=False,
        ),
    ]
