# Generated by Django 3.0.4 on 2020-03-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20200315_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeavingTime',
        ),
    ]
