# Generated by Django 3.0.4 on 2020-03-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_delete_leavingtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingDetails',
        ),
    ]
