# Generated by Django 3.0.4 on 2020-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20200315_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdetails',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
