# Generated by Django 3.0.4 on 2020-03-16 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20200316_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdetails',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
